# Generated by Django 2.2.5 on 2019-09-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AddField(
            model_name='city',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='gender',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
