# Generated by Django 2.2.5 on 2019-09-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20190911_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
