# Generated by Django 2.2.5 on 2019-09-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_dity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dity',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cities.City'),
            preserve_default=False,
        ),
    ]
