# Generated by Django 2.2.6 on 2019-11-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_dity_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.DeleteModel(
            name='Dity',
        ),
    ]
